version: "3.9"
services:
  nginx:
    image: nginx:1.27
    container_name: site-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on: []
  # you can also containerize the app if you prefer
  # app:
  #   build: ./site_app
  #   ports:
  #     - "8000:8000"
